version: "3"

services:
  mysql:
    image: mysql:8-debian
    platform: linux/amd64
    env_file:
      - ./server/.env
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    command: mysqld
    init: true

  express:
    build: ./server
    image: kawasawa-github-io_expressjs
    env_file:
      - ./server/.env
    environment:
      - MYSQL_HOST=mysql
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    volumes:
      - ./server/src:/app/src
    depends_on:
      - mysql
    init: true

volumes:
  mysql_volume:
    name: kawasawa-github-io_db
