version: "3"
name: kawasawa

services:
  kawasawa_db:
    image: mysql:8-debian
    platform: linux/amd64
    env_file:
      - ./server/.env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    command: mysqld
    init: true

  kawasawa_server:
    build: ./server
    image: kawasawa.github.io/express.js
    env_file:
      - ./server/.env
    environment:
      - MYSQL_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@kawasawa_db:${MYSQL_PORT}/${MYSQL_DATABASE}
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    volumes:
      - ./server/src:/app/src
    depends_on:
      - kawasawa_db
    init: true

volumes:
  mysql_volume:
    name: kawasawa_db
