FROM node:18.14.2-bullseye-slim

RUN mkdir -p /app
WORKDIR /app

COPY --chown=node:node ["package.json", ".yarnrc.yml", "./"]
RUN yarn install

COPY --chown=node:node . .
# RUN yarn build

USER node
EXPOSE 8080
# ENTRYPOINT ["yarn", "start"]
ENTRYPOINT ["yarn", "dev"]
