FROM node:18.14.2-bullseye-slim

RUN mkdir -p /app
WORKDIR /app

COPY --chown=node:node ["package.json", ".yarnrc.yml", "./"]
# ENV NODE_ENV production
# RUN yarn install --production
RUN yarn install

COPY --chown=node:node . .
# RUN yarn build

USER node
# ENTRYPOINT ["yarn", "start"]
ENTRYPOINT ["yarn", "dev"]
