# Generated by GitHub Copilot


class MCPServerConfig:
    """
    MCP サーバ設定
    """

    PROTOCOL_VERSION = "2024-11-05"
    SERVER_VERSION = "1.0.0"


class VectorSearchConfig:
    """
    ベクトル検索関連の設定
    """

    DEFAULT_USE_VECTOR_SEARCH = True
    DEFAULT_TOP_K = 10
    DEFAULT_SIMILARITY_THRESHOLD = 0.3
    CACHE_FILE_NAME = ".vector_cache.pkl"


class TextSearchConfig:
    """
    テキスト検索関連の設定
    """

    # コメントとして認識される行（正規表現リスト）
    COMMENT_PATTERNS = [
        r"^//\s*",  # JavaScript, TypeScript, C++等
        r"^#\s*",  # Python, Shell, YAML等
        r"^--\s*",  # SQL等
        r"^/\*\s*",  # CSS, Java等のブロックコメント開始
        r"^\*\s*",  # ブロックコメント内
        r"^<!--\s*",  # HTML
    ]

    # 除外するディレクトリ（バイナリファイルや大量のファイルを含むディレクトリ）
    EXCLUDED_DIRS = {
        "node_modules",
        ".git",
        "build",
        "dist",
        "coverage",
        "__pycache__",
        ".next",
        ".vscode",
        ".idea",
        "target",
        "vendor",
        "bin",
        "obj",
    }

    # 検索対象の拡張子
    TARGET_EXTENSIONS = {
        ".py",
        ".js",
        ".ts",
        ".tsx",
        ".jsx",
        ".java",
        ".cpp",
        ".c",
        ".h",
        ".hpp",
        ".cs",
        ".go",
        ".rs",
        ".php",
        ".rb",
        ".swift",
        ".kt",
        ".scala",
        ".sh",
        ".bash",
        ".zsh",
        ".sql",
        ".yml",
        ".yaml",
        ".json",
        ".xml",
        ".html",
        ".css",
        ".scss",
        ".less",
        ".vue",
        ".tf",
        ".dockerfile",
        ".md",
        ".txt",
        ".cnf",
        ".conf",
        ".cfg",
        ".ini",
        ".toml",
        ".properties",
        ".env",
        ".gitignore",
        ".gs",
    }

    # 拡張子なしのファイルも対象とする
    TARGET_NO_EXTENSION_FILES = {"dockerfile", "makefile", "readme"}
