# Generated by GitHub Copilot

from dataclasses import dataclass
from typing import List

import numpy as np


@dataclass
class KnowledgeEntity:
    """
    ナレッジエンティティのデータクラス
    型安全性を向上させるため、連想配列の代わりに使用する
    """

    file_path: str
    line_number: int
    content: str
    full_line: str
    file_extension: str


@dataclass
class VectorCache:
    """
    ベクトルキャッシュのデータクラス
    型安全性を向上させるため、連想配列の代わりに使用する
    """

    knowledge_list: List[KnowledgeEntity]
    vectors: np.ndarray
