# Generated by GitHub Copilot

import argparse
import asyncio
import sys
from pathlib import Path

from mcp_server import MCPServer


def main():
    """
    メイン関数
    コマンドライン引数からワークスペースパスとキーワードを取得してサーバを起動
    """

    # コマンドライン引数を取得
    parser = argparse.ArgumentParser(description="MCP Knowledge Server")
    parser.add_argument("--workspace", required=True, help="ワークスペースのルートパス")
    parser.add_argument(
        "--annotation_tag", default="NOTE:", help="抽出対象のアノテーションコメントタグ"
    )
    args = parser.parse_args()

    # ワークスペースパスの検証
    workspace_path = Path(args.workspace)
    if not workspace_path.exists() or not workspace_path.is_dir():
        print(f"エラー: 無効なワークスペースパス: {args.workspace}", file=sys.stderr)
        sys.exit(1)

    # サーバを起動
    mcp_server = MCPServer(str(workspace_path), args.annotation_tag)
    try:
        asyncio.run(mcp_server.run())
    except KeyboardInterrupt:
        print("サーバを停止しました", file=sys.stderr)


if __name__ == "__main__":
    main()
