# Generated by GitHub Copilot

import os
import re
from pathlib import Path
from typing import Dict, List, Tuple

from const import (
    COMMENT_PATTERNS,
    EXCLUDED_DIRS,
    TARGET_EXTENSIONS,
    TARGET_NO_EXTENSION_FILES,
)


class CommentSearcher:
    """
    コメントを検索・抽出するためのモジュール
    ワークスペース内のファイルを走査し、指定されたアノテーションコメントタグで始まるコメントを抽出する
    """

    def __init__(self, workspace_root: str, annotation_tag: str):
        """
        検索クラスの初期化
        Args:
            workspace_root (str): ワークスペースのルートディレクトリ
            annotation_tag (str): 抽出対象のアノテーションコメントタグ
        """
        self.workspace_root = Path(workspace_root)
        self.annotation_tag = annotation_tag

    def _should_exclude_dir(self, dir_path: Path) -> bool:
        """
        ディレクトリを除外すべきかどうかを判定
        Args:
            dir_path (Path): 判定対象のディレクトリパス
        Returns:
            bool: 除外すべきならTrue
        """
        return dir_path.name in EXCLUDED_DIRS

    def _should_include_file(self, file_path: Path) -> bool:
        """
        ファイルを検索対象に含めるべきかどうかを判定
        Args:
            file_path (Path): 判定対象のファイルパス
        Returns:
            bool: 含めるべきならTrue
        """
        if file_path.suffix == "":
            return file_path.name.lower() in TARGET_NO_EXTENSION_FILES
        return file_path.suffix.lower() in TARGET_EXTENSIONS

    def _is_comment_line(self, line: str) -> bool:
        """
        指定された行がコメント行かどうかを判定
        Args:
            line (str): 判定対象の行
        Returns:
            bool: コメント行の場合True
        """
        stripped_line = line.strip()
        if not stripped_line:
            return False
        for pattern in COMMENT_PATTERNS:
            if re.match(pattern, stripped_line):
                return True
        return False

    def _remove_comment_symbols(self, line: str) -> str:
        """
        行からコメント記号を除去
        Args:
            line (str): コメント記号を含む行
        Returns:
            str: コメント記号を除去した内容
        """
        content = line
        for pattern in COMMENT_PATTERNS:
            content = re.sub(pattern, "", content)
        return content.strip()

    def _is_annotation_line(self, line: str) -> bool:
        """
        指定された行にアノテーションコメントタグが含まれているかを判定
        Args:
            line (str): 判定対象の行
        Returns:
            bool: アノテーションコメントのタグが含まれている場合True
        """
        if self.annotation_tag not in line:
            return False
        # コメント記号を除去してからタグの存在確認
        content = self._remove_comment_symbols(line.strip())
        return self.annotation_tag in content

    def _extract_continuous_comment_lines(
        self, lines: List[str], start_index: int
    ) -> Tuple[List[str], int]:
        """
        指定されたインデックスから連続するコメント行を抽出
        Args:
            lines (List[str]): ファイルの全行
            start_index (int): 開始インデックス
        Returns:
            tuple[List[str], int]: (連続するコメント行のリスト, 次の処理インデックス)
        """
        continuous_lines = []
        j = start_index

        while j < len(lines):
            current_line = lines[j]

            # 空行はスキップして次の行をチェック
            if not current_line.strip():
                j += 1
                continue

            # コメント行でない場合は終了
            if not self._is_comment_line(current_line):
                break

            continuous_lines.append(current_line.strip())
            j += 1

        return continuous_lines, j

    def _create_note_entry(
        self, file_path: Path, line_number: int, continuous_lines: List[str]
    ) -> Dict[str, any]:
        """
        ノートエントリを作成
        Args:
            file_path (Path): ファイルパス
            line_number (int): 開始行番号
            continuous_lines (List[str]): 連続するコメント行
        Returns:
            Dict[str, any]: ノートエントリ
        """

        # 全体のコンテンツを結合（コメント記号を除去）
        content_lines = []
        for comment_line in continuous_lines:
            content = self._remove_comment_symbols(comment_line)
            # 空行でない場合のみ追加
            if content:
                content_lines.append(content)
        full_content = "\n".join(content_lines)

        return {
            "file_path": str(file_path.relative_to(self.workspace_root)),
            "line_number": line_number,
            "content": full_content,
            "full_line": " ".join(continuous_lines),
            "file_extension": file_path.suffix,
        }

    def _extract_notes_from_file(self, file_path: Path) -> List[Dict[str, any]]:
        """
        単一ファイルから対象のコメントを抽出
        Args:
            file_path (Path): 対象ファイルのパス
        Returns:
            List[Dict[str, any]]: 抽出されたコメントのリスト
        """

        notes = []

        try:
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = f.readlines()

            i = 0
            while i < len(lines):
                line = lines[i]
                line_num = i + 1

                # アノテーションコメントタグが含まれていない行はスキップ
                if not self._is_annotation_line(line):
                    i += 1
                    continue

                # アノテーションコメントの先頭行から連続するコメント行を抽出
                continuous_lines, next_index = self._extract_continuous_comment_lines(
                    lines, i
                )

                # コメント行がある場合のみノートエントリを作成
                if continuous_lines:
                    note_entry = self._create_note_entry(
                        file_path, line_num, continuous_lines
                    )
                    notes.append(note_entry)

                # 次の処理のためにインデックスを更新（最低でも1つは進める）
                i = max(next_index, i + 1)

        except Exception as e:
            # ファイル読み込みエラーは無視（バイナリファイル等）
            pass

        return notes

    def search_all_notes(self) -> List[Dict[str, any]]:
        """
        ワークスペース全体から対象の全コメントを検索
        Returns:
            List[Dict[str, any]]: 見つかったすべてのコメント
        """

        all_notes = []

        for root, dirs, files in os.walk(self.workspace_root):
            root_path = Path(root)

            # 除外ディレクトリをスキップ
            dirs[:] = [d for d in dirs if not self._should_exclude_dir(root_path / d)]

            for file in files:
                file_path = root_path / file

                # 検索対象のファイル以外はスキップ
                if not self._should_include_file(file_path):
                    continue

                # ファイルからコメントを抽出
                notes = self._extract_notes_from_file(file_path)
                all_notes.extend(notes)

        return all_notes

    def search_notes_by_keyword(self, search_keyword: str) -> List[Dict[str, any]]:
        """
        キーワードで対象のコメントを検索
        Args:
            search_keyword (str): 検索キーワード
        Returns:
            List[Dict[str, any]]: 検索にマッチしたコメント
        """

        filtered_notes = []

        search_keyword_lower = search_keyword.lower()
        all_notes = self.search_all_notes()

        for note in all_notes:
            # キーワードが含まれていない場合はスキップ（大文字小文字は区別しない）
            content_lower = note["content"].lower()
            if search_keyword_lower not in content_lower:
                continue
            filtered_notes.append(note)

        return filtered_notes

    def get_notes_by_file_path(self, file_path: str) -> List[Dict[str, any]]:
        """
        特定のファイルパスから対象のコメントを取得
        Args:
            file_path (str): 対象ファイルの相対パス
        Returns:
            List[Dict[str, any]]: 指定ファイル内の対象のコメント
        """

        target_file = self.workspace_root / file_path
        if not target_file.exists() or not target_file.is_file():
            return []
        if not self._should_include_file(target_file):
            return []
        return self._extract_notes_from_file(target_file)

    def get_notes_by_category(self) -> Dict[str, List[Dict[str, any]]]:
        """
        ファイル拡張子別に対象のコメントを分類
        Returns:
            Dict[str, List[Dict[str, any]]]: 拡張子別の対象のコメント
        """

        all_notes = self.search_all_notes()
        categorized = {}

        for note in all_notes:
            extension = note["file_extension"] or "no_extension"
            if extension not in categorized:
                categorized[extension] = []
            categorized[extension].append(note)

        return categorized
