# Generated by GitHub Copilot

import asyncio
import json
import os
import sys
from enum import IntEnum
from typing import Any, Dict, Optional

from searcher import CommentSearcher


class MCPServer:
    """
    ワークスペース内のコメントを検索・提供するMCPサーバ
    Model Context Protocol (MCP) を使用して、生成AIが指定のアノテーションコメントタグが付与されたコメントを情報源として活用できるようにする
    """

    def __init__(self, workspace_root: str, annotation_tag: str):
        """
        MCPサーバの初期化
        Args:
            workspace_root (str): ワークスペースのルートディレクトリ
            annotation_tag (str): 抽出対象のアノテーションコメントタグ
        """

        self.annotation_tag = annotation_tag
        self.searcher = CommentSearcher(workspace_root, annotation_tag)
        self.server_name = os.path.basename(os.path.dirname(os.path.abspath(__file__)))

    async def run(self):
        """
        MCPサーバを実行
        標準入力からJSONリクエストを読み取り、標準出力にレスポンスを出力
        """

        while True:
            try:
                # 標準入力から1行読み取り
                line = await asyncio.get_event_loop().run_in_executor(
                    None, sys.stdin.readline
                )
                if not line:
                    break

                # 先頭と末尾の空白を除去
                line = line.strip()
                if not line:
                    continue

                # JSONリクエストをパース
                try:
                    request = json.loads(line)
                except json.JSONDecodeError:
                    error_response = self._create_error_response(
                        MCPErrorCode.PARSE_ERROR, "無効なJSON"
                    )
                    print(json.dumps(error_response))
                    continue

                # リクエストを処理
                response = await self.handle_request(request)

                # レスポンスを出力
                print(json.dumps(response, ensure_ascii=False))
                sys.stdout.flush()

            except KeyboardInterrupt:
                break

            except Exception as e:
                error_response = self._create_error_response(
                    MCPErrorCode.INTERNAL_ERROR, f"内部エラー: {str(e)}"
                )
                print(json.dumps(error_response))

    async def handle_request(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """
        MCPリクエストを処理
        Args:
            request (Dict[str, Any]): MCPリクエスト
        Returns:
            Dict[str, Any]: MCPレスポンス
        """

        # NOTE: MCP プロトコルでは通信に JSON-RPC を用い、その際の method の名称に決まりがある
        #   必須
        #     initialize:     サーバ初期化
        #   任意
        #     tools/list:     ツール一覧取得
        #     tools/call:     ツール実行
        #     resources/list: リソース一覧取得
        #     resources/read: リソース読み取り
        #     prompts/list:   プロンプト一覧取得
        #     prompts/get:    プロンプト取得

        method = request.get("method")
        params = request.get("params", {})
        request_id = request.get("id")
        if method == "initialize":
            return self.handle_initialize(params, request_id)
        elif method == "tools/list":
            return self.handle_tools_list(params, request_id)
        elif method == "tools/call":
            return self.handle_tools_call(params, request_id)
        else:
            return self._create_error_response(
                MCPErrorCode.METHOD_NOT_FOUND, f"未知のメソッド: {method}", request_id
            )

    def handle_initialize(
        self, params: Dict[str, Any], request_id: str
    ) -> Dict[str, Any]:
        """
        初期化リクエストを処理
        Args:
            params (Dict[str, Any]): 初期化パラメータ
            request_id (str): リクエストID
        Returns:
            Dict[str, Any]: 初期化レスポンス
        """

        result = {
            "protocolVersion": "2024-11-05",
            "capabilities": {
                "tools": {"listChanged": False},
                "resources": {"subscribe": False, "listChanged": False},
            },
            "serverInfo": {"name": self.server_name, "version": "1.0.0"},
        }
        return self._create_response(result, request_id)

    def handle_tools_list(
        self, params: Dict[str, Any], request_id: str
    ) -> Dict[str, Any]:
        """
        利用可能なツール一覧を返す
        Args:
            params (Dict[str, Any]): リクエストパラメータ
            request_id (str): リクエストID
        Returns:
            Dict[str, Any]: ツール一覧レスポンス
        """

        tools = [
            {
                "name": "search_notes",
                "description": f"ワークスペース内の{self.annotation_tag}コメントをキーワードで検索します",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "keyword": {"type": "string", "description": "検索キーワード"}
                    },
                    "required": ["keyword"],
                },
            },
            {
                "name": "list_all_notes",
                "description": f"ワークスペース内のすべての{self.annotation_tag}コメントを一覧表示します",
                "inputSchema": {"type": "object", "properties": {}},
            },
            {
                "name": "get_notes_by_file",
                "description": f"指定されたファイルの{self.annotation_tag}コメントを取得します",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "file_path": {
                            "type": "string",
                            "description": "ファイルの相対パス",
                        }
                    },
                    "required": ["file_path"],
                },
            },
            {
                "name": "get_notes_by_category",
                "description": f"ファイル拡張子別に{self.annotation_tag}コメントを分類して取得します",
                "inputSchema": {"type": "object", "properties": {}},
            },
        ]
        return self._create_response({"tools": tools}, request_id)

    def handle_tools_call(
        self, params: Dict[str, Any], request_id: str
    ) -> Dict[str, Any]:
        """
        ツール呼び出しを処理
        Args:
            params (Dict[str, Any]): ツールパラメータ
            request_id (str): リクエストID
        Returns:
            Dict[str, Any]: ツール実行結果
        """

        tool_name = params.get("name")
        arguments = params.get("arguments", {})

        try:
            if tool_name == "search_notes":
                keyword = arguments.get("keyword", "")
                notes = self.searcher.search_notes_by_keyword(keyword)
                content = f"キーワード '{keyword}' で検索した結果: {len(notes)} 件\n\n"
                for note in notes:
                    content += f"📁 {note['file_path']}:{note['line_number']}\n"
                    content += f"💡 {note['content']}\n\n"
                result = {"content": [{"type": "text", "text": content}]}
                return self._create_response(result, request_id)

            elif tool_name == "list_all_notes":
                notes = self.searcher.search_all_notes()
                content = f"ワークスペース内のすべての{self.annotation_tag}コメント: {len(notes)} 件\n\n"
                for note in notes:
                    content += f"📁 {note['file_path']}:{note['line_number']}\n"
                    content += f"💡 {note['content']}\n\n"
                result = {"content": [{"type": "text", "text": content}]}
                return self._create_response(result, request_id)

            elif tool_name == "get_notes_by_file":
                file_path = arguments.get("file_path", "")
                notes = self.searcher.get_notes_by_file_path(file_path)
                content = f"ファイル '{file_path}' の{self.annotation_tag}コメント: {len(notes)} 件\n\n"
                for note in notes:
                    content += f"📍 行 {note['line_number']}\n"
                    content += f"💡 {note['content']}\n\n"
                result = {"content": [{"type": "text", "text": content}]}
                return self._create_response(result, request_id)

            elif tool_name == "get_notes_by_category":
                categorized_notes = self.searcher.get_notes_by_category()
                content = f"拡張子別の{self.annotation_tag}コメント分類:\n\n"
                for extension, notes in categorized_notes.items():
                    content += f"## {extension} ファイル ({len(notes)} 件)\n"
                    for note in notes:
                        content += f"📁 {note['file_path']}:{note['line_number']}\n"
                        content += f"💡 {note['content']}\n\n"
                    content += "\n"
                result = {"content": [{"type": "text", "text": content}]}
                return self._create_response(result, request_id)

            else:
                return self._create_error_response(
                    MCPErrorCode.METHOD_NOT_FOUND,
                    f"未知のツール: {tool_name}",
                    request_id,
                )

        except Exception as e:
            return self._create_error_response(
                MCPErrorCode.INTERNAL_ERROR, f"ツール実行エラー: {str(e)}", request_id
            )

    def _create_response(
        self, result: Any, request_id: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        MCP レスポンスを作成
        Args:
            result (Any): レスポンスデータ
            request_id (Optional[str]): リクエストID
        Returns:
            Dict[str, Any]: MCPレスポンス
        """

        response = {"jsonrpc": "2.0", "result": result}
        if request_id:
            response["id"] = request_id
        return response

    def _create_error_response(
        self, error_code: int, error_message: str, request_id: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        MCPエラーレスポンスを作成
        Args:
            error_code (int): エラーコード
            error_message (str): エラーメッセージ
            request_id (Optional[str]): リクエストID
        Returns:
            Dict[str, Any]: MCPエラーレスポンス
        """

        response = {
            "jsonrpc": "2.0",
            "error": {"code": error_code, "message": error_message},
        }
        if request_id:
            response["id"] = request_id
        return response


class MCPErrorCode(IntEnum):
    """
    MCP エラーコード定義
    JSON-RPC 2.0 仕様に基づいた標準エラーコード
    """

    # JSON-RPC 2.0 標準エラーコード
    INVALID_REQUEST = -32600  # 無効なリクエスト
    METHOD_NOT_FOUND = -32601  # メソッドが見つからない
    INVALID_PARAMS = -32602  # 無効なパラメータ
    INTERNAL_ERROR = -32603  # 内部エラー
    PARSE_ERROR = -32700  # 無効なJSON

    # MCP固有のエラーコード（-32000 から -32099 の範囲）
    TOOL_NOT_FOUND = -32000  # ツールが見つからない
    TOOL_EXECUTION_ERROR = -32001  # ツール実行エラー
